<a href="https://colab.research.google.com/github/khairahnh/Learn-to-Code/blob/main/Learning_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
n = 2

In [3]:
2 ** 3

8

In [4]:
120

120

In [5]:
2 ** 7 

128

In [6]:
x = 5

In [7]:
np.int8

numpy.int8

In [8]:
l = [0,1,2,3]


In [9]:
[i * 10 for i in l]


[0, 10, 20, 30]

In [10]:
a = np.array([0,1,2,3,4])

In [11]:
a.sum()

10

In [12]:
a.mean()

2.0

In [13]:
a.std()

1.4142135623730951

In [14]:
a.var()

2.0

In [15]:
A=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
A.sum()

45

In [17]:
A.mean()

5.0

In [18]:
A.std()

2.581988897471611

In [19]:
A.sum(axis=0)

array([12, 15, 18])

In [20]:
A.sum(axis=1)

array([ 6, 15, 24])

In [21]:
B=np.arange(5)
B+20

array([20, 21, 22, 23, 24])

#BOOLEAN ARRAYS

In [22]:
a=np.arange(4)

In [23]:
a

array([0, 1, 2, 3])

In [24]:
a[([0, -1])]

array([0, 3])

In [25]:
a[0], a[-1]

(0, 3)

In [26]:
a[[True, False, False, True]]

array([0, 3])

In [27]:
 a >= 2

array([False, False,  True,  True])

In [28]:
a[a >=2]

array([2, 3])

In [29]:
a.mean()

1.5

In [30]:
a[a > a.mean()]

array([2, 3])

In [31]:
a[~(a > a.mean())]

array([0, 1])

In [32]:
C = np.random.randint(100, size = (3,3))

In [33]:
C

array([[42, 91, 32],
       [53, 15, 69],
       [56, 98, 30]])

In [34]:
C[np.array([
    [True, False, True],
    [False, True, False],
    [True,False, True]
])]

array([42, 32, 15, 56, 30])

In [35]:
C > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [36]:
C [C > 30]

array([42, 91, 32, 53, 69, 56, 98])

#LINEAR ALGEBRA

In [37]:
D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [38]:
E = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [39]:
D.dot(E) #matrix multiplication

array([[20, 14],
       [56, 41],
       [92, 68]])

In [40]:
D @ E #matrix multiplication

array([[20, 14],
       [56, 41],
       [92, 68]])

In [41]:
E.T

array([[6, 4, 2],
       [5, 3, 1]])

In [42]:
E.T @ D

array([[36, 48, 60],
       [24, 33, 42]])

#SIZE OBJECTS IN MEMORY

INT, FLOATS

In [43]:
import sys
#an integer in python is > 24 bytes
sys.getsizeof(1)

28

In [44]:
#longs are even larger 
sys.getsizeof(10**100)

72

In [45]:
# numpy size is much smaller (numpy has smaller bytes or bits)
np.dtype(np.int8).itemsize

1

In [46]:
np.dtype(float).itemsize

8

In [47]:
sys.getsizeof([1])

80

In [48]:
np.array([1]).nbytes

8

#`performance is also important`

In [49]:
 l = list(range(1000)) #in python

In [50]:
t = np.arange(1000)

In [51]:
%time np.sum(t ** 2) #a lot of faster than in python. it takes 111 microseconds

CPU times: user 96 µs, sys: 0 ns, total: 96 µs
Wall time: 102 µs


332833500

In [52]:
%time sum((x ** 2 for x in l)) #it takes 283 microseconds

CPU times: user 436 µs, sys: 0 ns, total: 436 µs
Wall time: 602 µs


332833500

##USEFUL NUMPY FUNCTIONS

##random

In [53]:
np.random.random(size=2)

array([0.53406354, 0.03972715])

In [54]:
np.random.normal(size=2)

array([ 0.70164396, -1.32194598])

In [55]:
np.random.rand(2,4)

array([[0.62312001, 0.26813824, 0.74615671, 0.22056896],
       [0.67519784, 0.81373443, 0.85973271, 0.46199607]])

##arange

In [56]:
np.arange(10) #n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange (5,10) #n, n-1

array([5, 6, 7, 8, 9])

In [58]:
np.arange(0, 1., .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

##reshape

In [59]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [60]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

##linspace

In [61]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [62]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [63]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

#`ZEROS, ONES, EMPTY`

In [64]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [65]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
np.zeros((3,3), dtype=np.int_)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [68]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [70]:
np.empty((2,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

#`identity` and `eye`

In [71]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [72]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [73]:
np.eye(8,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [74]:
np.eye(8,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.eye(8,4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [76]:
"Hello World"[6]

'W'